### ISSUE TITLE
Создать копию кадра, добавить на ленту и открыть в редакторе

### ISSUE THREAD

**Issue by Nashev** [Nashev/MultiPult#124]
Открыть кадр на редактирование во внешнем редакторе. Следить за изменением чтоб перечитать миниатюру

**Comment by Nashev** [comment]
делать резервную копию

**Comment by Nashev** [comment]
открыть в редакторе вообще любой кадр. Меню из windows explorer показывать

**Comment by e-kaba** [comment]
Ага. Тогда нужно вот что в добавок:
Резервная копия в какой-нибудь спец-папке, А вернее вот как - оригинал остаётся где был и прячется, а на его месте открывается копия, сложенная в специальную папочку для редактированных кадров ) Что думаешь?

**Comment by Nashev** [comment]
А смысл?

**Comment by e-kaba** [comment]
Вроде уже поговорили. Мне технически всё равно как будет, лишь бы было )

**Comment by Nashev** [comment]
Всё это сделано, кроме автоматического перечитывания и показывания меню из windows explorer. Однако, есть показывание кадра в Windows explorer, и есть ручное перечитывание.
И есть затея #69 (Подхватывать кадры из папки по мере их поступления)
