### ISSUE TITLE
Резервные копии, дубли экземпляры...

### ISSUE THREAD

**Issue by e-kaba** [Nashev/MultiPult#127]
Возможно не туда пишу. Пробую )
Сейчас при копировании возникает кадр, являющийся ЭКЗЕМПЛЯРОМ уже имеющегося. Термин ЭКЗЕМПЛЯР принят во Флэше (может и ещё где) - можно его и придерживаться
Альтернативой экземпляру является ДУБЛЬ - дубль ничем не связан с исходным кадром - он просто его точная копия, до тех пор, пока мы в него как-нибудь не вмешались

Где хранить?
Экземпляры не надо хранить по определению.
Дубли храняться в специальной папке, так же как и снимки экрана

Добавление кадров... их добавляем, как и кадры с вебкамеры в разрыв ленты кадров, после текущего кадра. И в особую папку же. А будет ли особая папка одна на все случаи или их будет на каждый отдельно - это вопрос )

**Comment by Nashev** [comment]
Хорошо. Но подумаю ещё пока.

**Comment by e-kaba** [comment]
Вместо экземпляра у меня было какое-то другое слово.. но я его забыл и силюсь теперь вспомнить )

**Comment by e-kaba** [comment]
Дублировать доступ к кадру. это когда ярлык создаём
Дублировать изображение. Это когда полновесное копирование
 Только как пользователь будет узнавать, глядя на кадр с копией, что это такое?,  С чем он имеет дело? Чтоб  не удивлялся потом.   Ну, может и никак, только по памяти. Или по логике )
А можно предупреждать - к этому кадру есть другие доступы - вы собираетесь его менять... - как-то так

**Comment by Nashev** [comment]
Сделал дублирование файла в спец-папку, вариант с дублированием ссылки на один и тот же кадр пока считаю бесполезным и даже вредным, вносящим путаницу. Понятие ссылки таким образом обратно из лексикноа убрано. Вернее, внизу по горизонтали - лишь файлы, справа по вертикали - лишь ссылки.
