### ISSUE TITLE
Горячие клавиши для захвата изображений с веб-камеры

### ISSUE THREAD

**Issue by e-kaba** [Nashev/MultiPult#147]
В основном режиме
Для перехода к захвату с веб-камеры используем клавиши "+" или "=" (ну и ту и другую)

В окне захвата
Для возврата в основной режим - клавиша "Эскейп"
Клавиша "пробел" - выполняет захват

**Comment by Nashev** [comment]
сделано в версии 0.9.51, но несколько иначе. F6 переключает основное окно в режим захвата, Ctrl+F6 и клик по картинке с камеры открывает отдельное окно управления камерой, пробел берёт кадр.

@e-kaba  может и правда на клавиши = и Shift+= пересадить? с этого моего F6
