### ISSUE TITLE
Режим "Только картинка" для окна захвата с веб-камеры

### ISSUE THREAD

**Issue by e-kaba** [Nashev/MultiPult#148]
Клавиша "F" - переключает окно захвата в режим "Только картинка" и обратно
В режиме "Только картинка" окно предстаёт без всех элементов - только изображение с камеры. Мы можем за уголок менять его размер от нуля до полного экрана. Двойной клик в это окно разворачивает его на весь экран (по возможности, с чёрными полями, если ширина экрана больше чем ширина кадра) повторный двойной клик возвращает к прошлому размеру.

**Comment by Nashev** [comment]
сделано в версии 0.9.51, но несколько иначе
