### ISSUE TITLE
Управление программой из Лого Миров, через создание файлов, названных командами, и содержащими внутри параметры

### ISSUE THREAD

**Issue by Nashev** [Nashev/MultiPult#153]
В первую очередь нужна команда Grab для подсистемы захвата с камеры

**Comment by e-kaba** [comment]
А я-то думал, через обновление файла со стандартизованным именем, к которому прописан путь.
И выполнение команд из этого файла
Так хуже?

**Comment by Nashev** [comment]
Докинуть файлов-команд в папку легко, а вот дописать команд в файлик - как-то не очень. Правда, очередь команд врядли должна накапливаться, но мало-ли?... С другой стороны, файлы-команды в папке всё равно не особо упорядочены, какая из них очередь...

Как-то пока не хочется замахиватья на перспективу делать свой командный интерпретатор какого-нибудь языка программирования :)

**Comment by e-kaba** [comment]
командный файл просто сообщается, исполняется, рапортует об исполнении (куда? как?) и потом мы ждём нового такого же файла с командами
А?

**Comment by Nashev** [comment]
0.9.56 - при активной камере добавлено слежение за папкой, в которую будут сохраняться кадры, и при появлении в ней файла с именем grab он удаляется, а текущий кадр сохраняется в той же папке под именем Grabbed.png
