### ISSUE TITLE
Показывать предыдущий-следующий кадр

### ISSUE THREAD

**Issue by multistudia** [Nashev/MultiPult#38]
Предлагается отображать маленького размера вспомогательные превьюшки предыдущего (и последующего) кадров, дабы пользователь в процессе создания мультика видел, куда он попадёт после нажатия кнопки "Назад на кадр" (или, соответственно, "Вперёд на кадр").

Возможно, это может выглядеть так, как показано на прикреплённом изображении.

Необходимо добавить возможность отключения превьюшек в "Настройках". Возможно, стоит добавить возможность задания пользователем произвольного положения превьюшек на экране (например, визуально - путём перетаскивания мышкой с автоматическим запоминанием нового положения).

Подумать, быть может, имеет смысл выводить превью двух и более предыдущих (последующих) кадров.
![sample](https://f.cloud.github.com/assets/3661308/181148/b12b358c-7c47-11e2-844e-90e0dbd5d57e.jpg)

**Comment by Nashev** [comment]
Для начала - пару ненастраиваемых сделал. Захочется большего - сделаем ещё issue
