### ISSUE TITLE
Тач-шатл

### ISSUE THREAD

**Issue by e-kaba** [Nashev/MultiPult#46]
Хорошо что интерфейс управления прокруткой-записью мышово-клавиатурный. Что предлагаю добавить. Визуальное (экранное) колесо-шатл, которое можно крутить мышью (с тачпада) . Запуск по событию "касание колеса"
Для начала (а может вообще) удобно, чтобы был циферблат, разбитый на 24 деления (или на 12? - надо пробовать) и СТРЕЛКА - само колесо рисовать не обязательно

Вращая стрелку мы тем самым двигаемся по кадрам - частота вращения стрелки пропорциональна частоте сменяемых  кадров (если, 24 кадра = один оборот колеса - то квант - 15 градусов).
Уход за периферию колеса выключает его работу.
переход ближе к центру колеса - включает на автомат последнее состояние стрелки (движение с выбранной скоростью в выбранном направлении)

В процессе работы со стрелкой номер кадра отображается на конце стрелки а  превьюшка рядом или/и по центру циферблата? Где-то поблизости должна отображаться и текущая частота кадров

Клавиатура полностью работает - то есь, можно быстро пригать на метки, назначать метки и так далее.
Вот так для начала. потом можно будет на базе этого ещё что-то думать.

**Comment by e-kaba** [comment]
Очевидно, что область показа кадра - сектор, пересекаем его границу - мы в следующем секторе-кадре. Видимо, можно сразу показывать в секторах те кадры, которые будут публиковаться, по приходе в этот сектор. Будет вообще круто :)

**Comment by Nashev** [comment]
А в какой части рабочего экрана ты себе этот циферблат видишь?

**Comment by e-kaba** [comment]
Справа вижу, чтобы было удобно видеть при этом целое. Там у нас "таймлайн" сейчас.
Ну не знаю. Реально пока почти всё равно. Может быть внизу. 
При "полном экране" вижу всё это вместе с таймланом на другом мониторе.
Ну вот так примерно :)

Все превьюшки и другие финтифлюшки - потом.
Сперва просто стрелочка на циферблате и правило её осовной работы
Конкретно тащусь от всей идеи. Сделай, плз, побыстрее. Прям ваще офигеть как нравится.

**Comment by Nashev** [comment]
Сделал в версии 0.9.10, в первом приближении:
- Вызывается по F4 и из меню "Режим".
- Живёт в отдельном окне.
- Переходы учитывают телепорты.
- Центральная область включает автоматическую прокрутку с той скоростью, которая была замечена при последнем ручном переходе.
- При ручном управлении на треть круга до стрелки и треть круга после - отображаются миниатюры соответствующих кадров.
- В верхнем левом углу показывается частота кадров, замеченная при последнем ручном переходе - в том же виде, в каком оно отображается около метронома.

как-то так...
