### ISSUE TITLE
Шатл, колесо управления - движение назад должно сменять кадр сразу. Для двухфазовок.

### ISSUE THREAD

**Issue by Nashev** [Nashev/MultiPult#53]

**Comment by Nashev** [comment]
Не, тогда точка изменения кадра будет на бОльшем расстоянии от точки смены очередного кадра при движении по шатлу, и тоже нарушится ритмичность. Плохая идея.

**Comment by e-kaba** [comment]
Да я, вроде бы, приспоособился к этой теме. А вот с центральной частью, где включается автомат - так и не совладал. Не уверен, что это было хорошее решение.
