### ISSUE TITLE
В выбранной папке подхватывать картинки не только из корня папки, но и из её вложенных папок

### ISSUE THREAD

**Issue by Nashev** [Nashev/MultiPult#65]
В выбранной папке подхватывать картинки не только из корня папки, но и из любой степени вложенности папок (или, хотя бы, из папок верхнего уровня) всё в алфавитном порядке, причём, сперва фотки, потом все папки, в которых есть фотки, и в них так же рекурсивно.

**Comment by Nashev** [comment]
Для каждой новой папки ставить в начале метку

**Comment by Nashev** [comment]
Полезно, например, когда один мульт хочется собирать из комплектов, собранных с нескольких фотоаппаратов. В одну папку это всё не сложить, потому что могут имена фоток повторяться.

**Comment by e-kaba** [comment]
Не только поэтому. Ещё и потому, что они могут перепутаться, встать не в той последовательности

**Comment by Nashev** [comment]
**И самое главное - в качестве корня нужно будет уметь указать папку без фоток вовсе!**
То есть, надо для указания папки будет действительно выбирать папку, а не указывать фотку в папке и загружать её соседей. 

То есть, надо будет переделать способ указания папки с фотками. Потому что диалог выбора папки - он, конечно, есть, но он не показывает содержимое папок, а тут всё же видеть содержимое хотелось бы.
То есть, надо будет сделать свой интерфейс для выбора папки.

Отчасти, это перекликается с задачей #67 про панель слева для выбора возможного источника кадров. В ней можно сделать дерево папок и панельку просмотра миниатюр содержимого. Там же выключатель для #69 можно оформить...
