### ISSUE TITLE
Дать возможность задавать размеры кадра (ширину и высоту) при экспорте

### ISSUE THREAD

**Issue by Nashev** [Nashev/MultiPult#74]

**Comment by e-kaba** [comment]
При этом важно, что использоваться будут оригиналы картинок, то есть, можно будет делать HD, если снято с хорошим разрешением

**Comment by Nashev** [comment]
По хорошему, надо бы запоминать, каких размеров есть исходные кадры, и предлагать выбирать в том числе и из них. Если все кадры были одного размера - то, может быть, и не предлагать?..

С другой стороны, было бы полезно выписать [ряд стандартных размеров](http://ru.wikipedia.org/wiki/Display resolution#.D0.A0.D0.B0.D0.B7.D1.80.D0.B5.D1.88.D0.B5.D0.BD.D0.B8.D0.B5_.D1.8D.D0.BA.D1.80.D0.B0.D0.BD.D0.B0_.D0.BC.D0.BE.D0.BD.D0.B8.D1.82.D0.BE.D1.80.D0.B0), и предлагать и их тоже...

**Comment by Nashev** [comment]
Выписал пока сюда и лишь эти:
4:3 / 
QVGA    320×240
VGA 640×480
SVGA    800×600
XGA 1024×768
XGA+    1152×864
SXGA+   1400×1050
UXGA    1600×1200
QXGA    2048×1536
QUXGA   3200×2400
HUXGA   6400×4800
16:9    / 
nHD 640×360
FWVGA   854×480
qHD 960x540
HD 720p 1280×720
WXGA++  1600×900
Full HD 1080p   1920×1080
QWXGA   2048×1152
WQXGA   2560×1440
Super Hi-Vision 7680×4320
