### ISSUE TITLE
Мышиный пульт управления

### ISSUE THREAD

**Issue by Nashev** [Nashev/MultiPult#83]
Где-то рядом с окошком шаттла/штурвала, возможно в нём же, завести стопку кнопок-качелек, для переходов по кадрам/меткам вперёд-назад путём нажатия левой или правой кнопок мыши.

**Comment by Nashev** [comment]
А может, в конце строки кадров сделать маленькую область переходов мышкой вперёд-назад?

Типа, как стрелки на полосе прокрутки у на макинтошах, обе с одного краю полосы прокрутки, но вот ещё с такой фичей, что правая/левая кнопки мыши в разные стороны крутят. Пояснение про такую возможность - во всплывающей подсказке там сделать.

**Comment by e-kaba** [comment]
Не совсем понял. Может быть встретиться и пообсуждать.
Я имел в виду вертикальный такой пульт, на котором в зависимости от зоны по вертикали кнопки мыши выполняли бы разные функции. Экспериментировать надо.

**Comment by Nashev** [comment]
А вот кстати, можешь эти разные функции перечислить?
1) Шагнуть на один кадр и остановиться
2) Шагать по кадру, пока нажато
3) Начать шагать, и не останавливаться когда отпустят, а шагать пока что-то другое не скомандуют (?)
?

**Comment by Nashev** [comment]
А про маленькую область - это в дополнение к большому пульту, на одну только вторую функцию из перечисленных мною, например.

**Comment by e-kaba** [comment]
1. \- это не одна позиция а ряд разных скоростей (я так думаю - может и не правильно)
   3 - второй щелчок в ту же сторону должен останавливать

**Comment by e-kaba** [comment]
Только не очень понял, где эта область находится :(

**Comment by Nashev** [comment]
В первом приближении мышиный пульт буду считать принятым, если что - изменения как новые issue зарегистрируем.
