### ISSUE TITLE
Финальный рекламный кадр

### ISSUE THREAD

**Issue by Nashev** [Nashev/MultiPult#84]
В конце полосы записанного фильма (той, что справа, вертикальная) сделать отдельную рамку, символизирующую рекламную заставку, и она будет отодвигаться по мере записи. При воспроизведении - последним кадром показывать её.

Когда появится возможность фрагменты записанного таскать мышкой, добавлять/удалять/переставлять - эта рамка-заставка будет одним из таких фрагментов, но "приклеенная" и не удаляемая.

**Comment by Nashev** [comment]
Конфликтец логики небольшой: при переходе на рекламный кадр тыканием мышью в правой ленте - на основном экране наверно таки должен оказываться этот кадр. Но сейчас у нас центральный экран показывает лишь текущие кадры из доступных источников - и при проигрывании фильма - по сути, тоже. А тут - получается, что он должен показать кадр, которого в источниках нету. Нужно как-то переосмыслить центральный экран по такому случаю... Это же касается и всей затеи #67 - той, что с фрагментами, источниками, приёмниками и т.п..

Но пока можно сделать вид, что его нету.

**Comment by e-kaba** [comment]
Привет!
Сжимаю "полные кадры без сжатия". Результат не совпадает по синхрону с записанным материалом (каков он на самом деле и во внутреннем формате, где всё вроде бы более-менее точно).
Возможно тут большую роль играет финальная табличка. (связано с #10)

**Comment by Nashev** [comment]
В первом приближении рекламный кадр буду считать принятым, если что - изменения как новые issue зарегистрируем.
