### ISSUE TITLE
По умолчанию сделать кодек без сжатия (потому что остальные доступные убоги), и ещё - сохранять последний выбранный.

### ISSUE THREAD

**Issue by Nashev** [Nashev/MultiPult#90]

**Comment by e-kaba** [comment]
Приложить приличный набор кодеков! Желательно бесплатных, конечно. Если такое имеется.
Приложить список хороших программ поддержки, чтобы их можно было ставить.
Например, аудасити, виртуалдубмод, ВиЭльСи, и так далее...
Как приложить? Дать ссылки. Где? Вопрос...
